// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */
import { type RouteType as Route_0 } from "./src/app/example/[slug]/routeType";
import { type RouteType as Route_1 } from "./src/app/example/routeType";
import type { InferRoute, StaticRoute } from "next-typesafe-url";

declare module "@@@next-typesafe-url" {
  interface DynamicRouter {
    "/example/[slug]": InferRoute<Route_0>;
    "/example": InferRoute<Route_1>;
  }

  interface StaticRouter {
    "/": StaticRoute;
  }
}
